#!/bin/sh
set -e
[ -x /usr/bin/update-desktop-database ] && update-desktop-database -q || true
[ -x /usr/bin/gtk-update-icon-cache ] && gtk-update-icon-cache -q /usr/share/icons/hicolor || true
exit 0
